"""Smoke test for ggplot2_py._biobabel.

Generated by `biobabel new contract`. Edit to actually exercise the package's
public API (this template only verifies importability).
"""

from __future__ import annotations


def main() -> None:
    import ggplot2_py  # noqa: F401
    print("imported ggplot2_py successfully")


if __name__ == "__main__":
    main()
